/**
 * OpenCV.js wrapper for Node.js environment
 * Auto-generated by auto-image-diff setup script
 */

const fs = require('fs');
const path = require('path');

// Load the OpenCV.js module
const opencvPath = path.join(__dirname, 'node_modules', '@techstark', 'opencv-js', 'dist', 'opencv.js');
const Module = {
  wasmBinaryFile: 'opencv.wasm',
  onRuntimeInitialized: () => {
    console.log('OpenCV.js initialized successfully');
  },
  print: (text) => console.log(text),
  printErr: (text) => console.error(text),
};

// Execute the OpenCV.js script
const opencvScript = fs.readFileSync(opencvPath, 'utf8');
eval(opencvScript);

// Export cv object
module.exports = cv;
