#!/usr/bin/env node

/**
 * Post-install script to set up OpenCV.js
 * This ensures OpenCV is properly configured after npm install
 */

const fs = require('fs');
const path = require('path');

console.log('🔧 Setting up OpenCV.js for auto-image-diff...');

// Check if @techstark/opencv-js is installed
const opencvPath = path.join(__dirname, '..', 'node_modules', '@techstark', 'opencv-js');
if (!fs.existsSync(opencvPath)) {
  console.log('✅ OpenCV.js package not found - skipping setup (optional dependency)');
  process.exit(0);
}

// Create a wrapper file for proper OpenCV loading in Node.js
const wrapperContent = `/**
 * OpenCV.js wrapper for Node.js environment
 * Auto-generated by auto-image-diff setup script
 */

const fs = require('fs');
const path = require('path');

// Load the OpenCV.js module
const opencvPath = path.join(__dirname, 'node_modules', '@techstark', 'opencv-js', 'dist', 'opencv.js');
const Module = {
  wasmBinaryFile: 'opencv.wasm',
  onRuntimeInitialized: () => {
    console.log('OpenCV.js initialized successfully');
  },
  print: (text) => console.log(text),
  printErr: (text) => console.error(text),
};

// Execute the OpenCV.js script
const opencvScript = fs.readFileSync(opencvPath, 'utf8');
eval(opencvScript);

// Export cv object
module.exports = cv;
`;

const wrapperPath = path.join(__dirname, '..', 'opencv-loader.js');
fs.writeFileSync(wrapperPath, wrapperContent);

console.log('✅ OpenCV.js setup completed successfully!');
console.log('📝 Created opencv-loader.js wrapper for Node.js environment');